spring.application.name=inscripcionplatform

#Configuracion base de datos
spring.datasource.url=jdbc:oracle:thin:@todolodemas
spring.datasource.username=ADMIN
spring.datasource.password=Password_123
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

#PARAMETROS PARA PODER REVISAR LA APP DESDE OTRA IP
#spring.datasource.url=jdbc:h2:mem:inscripcionplatform
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8080