spring.application.name=inscripcionplatform

#Configuracion base de datos Oracle Cloud
spring.datasource.url=spring.datasource.url=jdbc:oracle:thin:@${DB_DSN}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true


#Para conectarse a la base de datos MySQL dockerizada#
#spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g9e2ad316f41c2c_backenddb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
#spring.datasource.username=ADMIN
#spring.datasource.password=Password_123
#spring.datasource.driverClassName=oracle.jdbc.OracleDriver


#PARAMETROS PARA PODER REVISAR LA APP DESDE OTRA IP
#spring.datasource.url=jdbc:h2:mem:inscripcionplatform
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8080